%% Use-case diagram for Rodovi Lanches
%% Actors: Garcom, Cozinha, Balcao, Gerente
sequenceDiagram
    participant Garcom
    participant Api
    participant Cozinha
    participant Balcao
    Garcom->>Api: Criar Pedido
    Api->>Cozinha: Envia Pedido
    Cozinha->>Cozinha: Preparar
    Cozinha->>Api: Marcar Pronto
    Api->>Balcao: Notifica Pedido Pronto
    Balcao->>Api: Receber Pagamento
    Api->>Gerente: Relatórios
